language: c
compiler:
  - gcc
  - clang

env:
  global:
    - OMP_NUM_THREADS=4
    - THREADSAFE=1
    - OPENMP=1
  matrix:
    - CODE=ORIGINAL_ONLY
    - CODE=SSE_INTRINSICS
    - CODE=VECTOR_EXTENSIONS
    - THREADSAFE=0
    - OPENMP=0

matrix:
  exclude:
    - compiler: clang
      env: CODE=VECTOR_EXTENSIONS

script: make && make test
