language: c
compiler:
  - gcc
  - clang

env:
  - GF_MODE=NORMAL
  - GF_MODE=SSE_INTRIN
  - GF_MODE=VECTOR_EXT

matrix:
  exclude:
    - compiler: clang
      env: GF_MODE=VECTOR_EXT

script: make CPPFLAGS="-DGF_BITS=16 -DENABLE_$GF_MODE" && make test
